### ISSUE TITLE
convert_pdf may capture errant pages and make the created file too long

### ISSUE THREAD

**Issue by anthonysalvato3** [freelawproject/bankruptcy-parser#76]
Normally, pages unrelated to the inputted form are skipped with this line:
```
if text[-300:].find(form) == -1:
                continue
```

But in rare situations when other forms reference the current form name being converted, some of those other form's pages can be captured. The result is the created file will append a number of additional pages equal to the amount of false positives.

I am proposing adding logic to modify the page list such that it uses the sublist of itself with the largest number of consecutive pages:

```
# Retrieve the longest sequence of consecutive pages, in case errant pages are captured
    longest_sublist = []
    current_sublist = [pages[0]]

    for i in range(1, len(pages)):
        if pages[i] == pages[i - 1] + 1:
            current_sublist.append(pages[i])
        else:
            if len(current_sublist) > len(longest_sublist):
                longest_sublist = current_sublist
            current_sublist = [pages[i]]

    # After the loop, check if the last current sublist is the longest
    if len(current_sublist) > len(longest_sublist):
        longest_sublist = current_sublist

    pages = longest_sublist
```

**Comment by mlissner** [comment]
How does this feel to you, @flooie ?

**Comment by flooie** [comment]
This is not doubting this - but could you add some screenshots of examples pages for reference?

**Comment by flooie** [comment]
~~Also @anthonysalvato3 did you see my last message on the closed PR?  Should we just wrap that one up if we have a completed solution?~~

never mind - see it now

**Comment by mlissner** [comment]
It feels like if we have test cases on all our PRs, it'd be really easy to know if this kind of logic was working.

**Comment by anthonysalvato3** [comment]
Here is an example situation (with an unsupported form, but still applicable) where if I want to parse 206A/B, the text shows in the last 300 characters of this page, so it counts.
![image](https://github.com/freelawproject/bankruptcy-parser/assets/17511454/5fac96f3-f2f9-4801-b5d1-822b54593b7a)

**Comment by flooie** [comment]
Thanks - I found an example in our test files as well.  Im looking at a fix - because I think your example code - will leave it vulnerable to another potential bug.

**Comment by flooie** [comment]
@anthonysalvato3 

What about this ... 

we change drop the page requirement because I came across an example that does not use page 1 of X in reviewing other form names.  And just create a nice regex.

This regex pattern finds occurrences of a target form with optional word boundaries or parentheses around it (see some form with wrapped parentheses, while also excluding matches where the words "Official Form" come after the target string.  This avoids finding anything but the final form.  



```
    pages = []
    with pdfplumber.open(filepath) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if text[-300:].find(form) == -1:
                continue
            if text[-300:].lower().find("page") == -1:
                continue
            pages.append(page.page_number - 1)

    if not pages:
        return False

```

to 

```
    pages = []
    with pdfplumber.open(filepath) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            pattern = r"(?<!\w)(?:\(|\b){}(?:\)|\b)(?!\w(.*Official Form))".format(
                re.escape(form)
            )
            if not re.findall(pattern, text[-300:]):
                continue
            pages.append(page.page_number - 1)

    if not pages:
        return False
```

**Comment by flooie** [comment]
I simplified it a little more in the PR.

Added two tests.  Would appreciate your feedback and testing though @anthonysalvato3

**Comment by flooie** [comment]
I didnt think the looping would avoid the issue of one page forms - having a second or third incorrectly labeled page.  And I thought the regex pattern that only finds the form if it is the last usage of official form on the page was cleaner.

**Comment by anthonysalvato3** [comment]
I only have 1 test example of my own but it works on that, and I like the solution because mine wasn't very well thought-out.

**Comment by flooie** [comment]
@anthonysalvato3 do you use the docker image or would a pypi bump be sufficient for your current usage
